---
title: "Longer-Term All-Cause and Cardiovascular Mortality  With Intensive Blood Pressure Control"
subtitle: "A Secondary Analysis of a Randomized Clinical Trial"
author: 
- Byron C Jaeger
- Adam P Bress
- Joshua D Bundy
- Alfred K Cheung
- William C Cushman
- Paul E Drawz
- Karen C Johnson
- Cora E Lewis
- Suzanne Oparil
- Michael V Rocco
- Stephen R Rapp
- Mark A Supiano
- Paul K Whelton
- Jeff D Williamson
- Jackson T Wright
- David M Reboussin
- Nicholas M Pajewski
date: '2022-11-01'
categories:
  - Research 
  - Blood pressure
  - Cardiovascular disease
  - SPRINT
links:
- icon: file-richtext-fill
  name: Publication
  url: https://jamanetwork.com/journals/jamacardiology/article-abstract/2797064
- icon: github
  name: Code
  url: https://github.com/bcjaeger/sprint-mortality-ndi
- icon: newspaper
  name: News articles
  url: https://jamanetwork.altmetric.com/details/137107938/news
---

**Note**: The linked repo for this paper has been updated since the paper's publication as more recent national death index data have become available.

#### Importance

The Systolic Blood Pressure Intervention Trial (SPRINT) showed that intensive blood pressure control reduced cardiovascular morbidity and mortality. However, the legacy effect of intensive treatment is unknown.

#### Objective

To evaluate the long-term effects of randomization to intensive treatment with the incidence of cardiovascular and all-cause mortality approximately 4.5 years after the trial ended.

#### Design, Setting, and Participants

In this secondary analysis of a multicenter randomized clinical trial, randomization began on November 8, 2010, the trial intervention ended on August 20, 2015, and trial close-out visits occurred through July 2016. Patients 50 years and older with hypertension and increased cardiovascular risk but without diabetes or history of stroke were included from 102 clinic sites in the US and Puerto Rico. Analyses were conducted between October 2021 and February 2022.

#### Interventions

Randomization to systolic blood pressure (SBP) goal of less than 120 mm Hg (intensive treatment group; n=4678) vs less than 140 mm Hg (standard treatment group; n=4683).

#### Main Outcomes and Measures

Extended observational follow-up for mortality via the US National Death Index from 2016 through 2020. In a subset of 2944 trial participants, outpatient SBP from electronic health records during and after the trial were examined.

#### Results

Among 9361 randomized participants, the mean (SD) age was 67.9 (9.4) years, and 3332 (35.6%) were women. Over a median (IQR) intervention period of 3.3 (2.9-3.9) years, intensive treatment was beneficial for both cardiovascular mortality (hazard ratio [HR], 0.66; 95% CI, 0.49-0.89) and all-cause mortality (HR, 0.83; 95% CI, 0.68-1.01). However, at the median (IQR) total follow-up of 8.8 (8.3-9.3) years, there was no longer evidence of benefit for cardiovascular mortality (HR, 1.02; 95% CI, 0.84-1.24) or all-cause mortality (HR, 1.08; 95% CI, 0.94-1.23). In a subgroup of participants, the estimated mean outpatient SBP among participants randomized to intensive treatment increased from 132.8 mm Hg (95% CI, 132.0-133.7) at 5 years to 140.4 mm Hg (95% CI, 137.8-143.0) at 10 years following randomization.

#### Conclusions and Relevance

The beneficial effect of intensive treatment on cardiovascular and all-cause mortality did not persist after the trial. Given increasing outpatient SBP levels in participants randomized to intensive treatment following the trial, these results highlight the importance of consistent long-term management of hypertension.
