project:
  type: website

website:
  title: "Byron Jaeger"
  drafts:
    - blog/posts/2024-08-17_aorsf-survival.qmd
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: project/index.qmd
        text: Projects
      - href: publication/index.qmd
        text: Publications
      - href: talk/index.qmd
        text: Talks
      - href: blog/index.qmd
        text: Blog


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

