project:
  type: website

website:
  title: "Byron Jaeger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: project/index.qmd
        text: Projects
      - href: publication/index.qmd
        text: Publications
      - href: talk/index.qmd
        text: Talks
      - href: blog/index.qmd
        text: Blog
      - href: https://bcjaeger.github.io/cv/
        text: CV


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

